---
- name: Web server setup
  hosts: all

  tasks:
   - name: Install httpd
     become: yes
     ansible.builtin.yum:
       name: httpd
       state: present
   - name: start httpd service
     become: yes
     ansible.builtin.service:
       name: httpd
       state: started
       enabled: yes
