---
- name: Web server setup
  hosts: webservers
  become: yes
  tasks:
   - name: Install httpd
     ansible.builtin.yum:
       name: httpd
       state: present
   - name: start httpd service
     ansible.builtin.service:
       name: httpd
       state: started
       enabled: yes
